name: example
description: A sample Dart application demonstrating MQTT client functionality.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mqtt_client: ^9.6.1
  mqtt5_client: ^4.2.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
